
[server]
headless = true
address = "0.0.0.0"
port = 8080

[theme]
primaryColor="#2E8B57"  # Forest green
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
